### PR TITLE
Add support for Linux desktop platform

### PR DESCRIPTION
**Pull request by freshtechtips**
This is just the very first steps of adding support for Linux, it's not ready yet, but I will complete this soon, let me know if you are interested in adding support for Linux

[Feature request](https://github.com/natsuk4ze/gal/issues/163)

It also needs more testing on different Linux distros and I will soon.

### CODE REVIEW

**Comment by freshtechtips** [comment]
Hi @natsuk4ze

You might want to consider reviewing the code before I go further

**Comment by natsuk4ze** [comment]
Can we move linux folder which linux related to top level?
It should not to put code under `lib/` that is only used on Linux. [Federated plugins](https://docs.flutter.dev/packages-and-plugins/developing-packages#federated-plugins) might be possible.

**Comment by freshtechtips** [comment]
- [ ] > Can we move linux folder which linux related to top level?
> It should not to put code under `lib/` that is only used on Linux. [Federated plugins](https://docs.flutter.dev/packages-and-plugins/developing-packages#federated-plugins) might be possible.

The linux folder contains dart code. How will we use the dart code that is outside of the lib?? The name of the linux folder doesn't matter much matter it could be anything

The only way is to move the implementation to native code using method channel 

I prefer doing it the way we are doing right now, but if insisted, let me know, so I move everything to native code

**Comment by freshtechtips** [comment]
> Can we move linux folder which linux related to top level? It should not to put code under `lib/` that is only used on Linux. [Federated plugins](https://docs.flutter.dev/packages-and-plugins/developing-packages#federated-plugins) might be possible.

Hi again, this is a message just in case you missed the notification.

**Comment by freshtechtips** [comment]
I will return to Linux support later but it looks like I will need more time

**Comment by natsuk4ze** [comment]
Understood. I appreciate your work @freshtechtips . 
There is no need to rush. Originally, adding a platform should be a prudent thing to do.

I will always accept high quality PR that meets the requirements.
Thank you again 💚

**Comment by freshtechtips** [comment]
> Understood. I appreciate your work @freshtechtips . 
> There is no need to rush. Originally, adding a platform should be a prudent thing to do.
> 
> I will always accept high quality PR that meets the requirements.
> Thank you again 💚

Hi again, thank you for your understanding 

The main reason why I closed it is because this whole PR added support for Linux in dart code, and it requires checking if the platform is Linux every time for all platforms 

Next time it will be in C++ native Linux code

**Pull request closed without merging**
