### PR TITLE
Added name parameter in putImageBytes

### LINKED ISSUE #204: Adding a name parameter in putImageBytes
### Did you check the documentation and it did not help?

- [X] I have carefully read the [README](https://github.com/natsuk4ze/gal/blob/main/README.md)
- [X] I have carefully searched the [existing documentation](https://github.com/natsuk4ze/gal/wiki)
- [X] I have carefully searched the [existing answer](https://github.com/natsuk4ze/gal/discussions)
- [X] I have carefully read the [contribution guide](https://github.com/natsuk4ze/gal/blob/main/CONTRIBUTING.md)

### Proposal

I believe adding a 'name' parameter in putImageBytes method will enable developer to give custom names for any image to be saved in gallery. 

### Use case

I think having 'image' name for every saved image can cause confusion to the user. Especially for applications like collage maker where devs might prefer to save the image with collage name defined by user.

### PR DESCRIPTION
**Pull request by noob8boi**
## Overview

_Please change this text to a brief statement of purpose or overview._

- [ ] I read the [Contributor Guide](https://github.com/natsuk4ze/gal/blob/main/CONTRIBUTING.md) and followed the process outlined there for submitting PRs.

## Related Issues

- Close #204

### CODE REVIEW

**Comment by natsuk4ze** [comment]
Thank you for submitting this PR @noob8boi 
Do you plan to implement it on platforms other than Android? If not, I will take over the work.

**Comment by noob8boi** [comment]
> Thank you for submitting this PR @noob8boi Do you plan to implement it on platforms other than Android? If not, I will take over the work.

I can try!

**Comment by natsuk4ze** [comment]
> I can try for iOS

OK. I think you can use [originalFilename in PHAssetResourceCreationOptions](https://developer.apple.com/documentation/photokit/phassetresourcecreationoptions) for 

```swift
private func putMediaBytes(
  bytes: Data, album: String?, completion: @escaping (Bool, Error?) -> Void
) {
  writeContent(
    assetChangeRequest: {
      let request = PHAssetCreationRequest.forAsset()
      request.addResource(with: .photo, data: bytes, options: //HERE)
      return request
    }, album: album, completion: completion
  )
}
```
And mention me when you have finished the work.

**Comment by noob8boi** [comment]
> > I can try for iOS
> 
> OK. I think you can use [originalFilename in PHAssetResourceCreationOptions](https://developer.apple.com/documentation/photokit/phassetresourcecreationoptions) for
> 
> ```swift
> private func putMediaBytes(
>   bytes: Data, album: String?, completion: @escaping (Bool, Error?) -> Void
> ) {
>   writeContent(
>     assetChangeRequest: {
>       let request = PHAssetCreationRequest.forAsset()
>       request.addResource(with: .photo, data: bytes, options: //HERE)
>       return request
>     }, album: album, completion: completion
>   )
> }
> ```
> 
> And mention me if you have finished the work or need help.

sure may i know whats your deadline for this?

**Comment by natsuk4ze** [comment]
> sure may i know whats your deadline for this? just making sure if its ok to work on it tomorrow or day after tomorrow

It means to add it at the `opions`. I just finished adding the windows platform. I have time now, can I take over the process?

**Comment by noob8boi** [comment]
> > sure may i know whats your deadline for this? just making sure if its ok to work on it tomorrow or day after tomorrow
> 
> It means to add it at the `opions`. I just finished adding the windows platform. I have time now, can I take over the process?

for sure i dont mind.. thank you!

**Comment by natsuk4ze** [comment]
> for sure i dont mind.. thank you!

OK. Thanks👍

**Review by natsuk4ze — APPROVED** [review]

**Review by natsuk4ze — APPROVED** [review]

**Pull request merged**
